import { Company } from "./types";

export const MOCK_COMPANIES: Company[] = [
  {
    id: "1",
    name: "NovaPay",
    website: "https://novapay.io",
    description: "AI-powered payment infrastructure for emerging markets. NovaPay enables instant cross-border transactions with intelligent fraud detection and compliance automation.",
    sector: "FinTech",
    stage: "Series A",
    location: "San Francisco, CA",
    founded: 2021,
    employees: "51-100",
    tags: ["payments", "AI", "cross-border", "compliance"],
    signals: [
      { date: "2024-11-15", event: "Raised $12M Series A led by a16z" },
      { date: "2024-09-01", event: "Launched in 3 new African markets" },
      { date: "2024-06-20", event: "Partnership with Stripe announced" },
    ],
  },
  {
    id: "2",
    name: "LexiAI",
    website: "https://lexiai.com",
    description: "Contract analysis platform using large language models to automate legal document review, clause extraction, and risk assessment for enterprise legal teams.",
    sector: "LegalTech",
    stage: "Seed",
    location: "New York, NY",
    founded: 2023,
    employees: "11-50",
    tags: ["legal", "NLP", "contracts", "enterprise"],
    signals: [
      { date: "2024-10-10", event: "Closed $4M seed round" },
      { date: "2024-08-05", event: "Launched enterprise beta with 20 law firms" },
    ],
  },
  {
    id: "3",
    name: "MediSync",
    website: "https://medisync.health",
    description: "Interoperability platform connecting hospital EHR systems with wearable health data, enabling real-time patient monitoring and predictive diagnostics.",
    sector: "HealthTech",
    stage: "Series B",
    location: "Boston, MA",
    founded: 2019,
    employees: "101-250",
    tags: ["healthcare", "EHR", "wearables", "diagnostics", "interoperability"],
    signals: [
      { date: "2024-12-01", event: "Series B of $28M closed" },
      { date: "2024-07-15", event: "FDA clearance for predictive algorithm" },
      { date: "2024-03-10", event: "Expanded to 150 hospitals nationwide" },
    ],
  },
  {
    id: "4",
    name: "CloudMetrics",
    website: "https://cloudmetrics.dev",
    description: "Developer-first observability platform with AI-powered anomaly detection. Unified logs, metrics, and traces with natural language querying.",
    sector: "SaaS",
    stage: "Series A",
    location: "Austin, TX",
    founded: 2022,
    employees: "51-100",
    tags: ["observability", "devtools", "AI", "monitoring"],
    signals: [
      { date: "2024-11-01", event: "Hit $3M ARR milestone" },
      { date: "2024-08-20", event: "Launched natural language query feature" },
    ],
  },
  {
    id: "5",
    name: "TerraOffset",
    website: "https://terraoffset.co",
    description: "Marketplace for verified carbon credits with blockchain-based tracking and transparent impact reporting for corporate sustainability programs.",
    sector: "Climate",
    stage: "Seed",
    location: "London, UK",
    founded: 2023,
    employees: "11-50",
    tags: ["carbon credits", "blockchain", "sustainability", "marketplace"],
    signals: [
      { date: "2024-10-25", event: "Partnered with 3 Fortune 500 companies" },
      { date: "2024-07-01", event: "Seed round of $5M from Climate VC" },
    ],
  },
  {
    id: "6",
    name: "FleetMind",
    website: "https://fleetmind.io",
    description: "AI-driven fleet optimization platform that reduces fuel costs and delivery times through real-time route planning and predictive maintenance.",
    sector: "Logistics",
    stage: "Pre-Seed",
    location: "Chicago, IL",
    founded: 2024,
    employees: "1-10",
    tags: ["logistics", "AI", "fleet", "optimization"],
    signals: [
      { date: "2024-09-15", event: "Completed Y Combinator W24 batch" },
    ],
  },
  {
    id: "7",
    name: "DataWeave",
    website: "https://dataweave.ai",
    description: "No-code data pipeline builder with AI-powered transformations. Connect any data source and build production-ready ETL workflows in minutes.",
    sector: "DataTech",
    stage: "Series A",
    location: "Seattle, WA",
    founded: 2021,
    employees: "51-100",
    tags: ["data", "no-code", "ETL", "pipelines", "AI"],
    signals: [
      { date: "2024-11-20", event: "Raised $15M Series A" },
      { date: "2024-06-10", event: "Reached 1,000 paying customers" },
    ],
  },
  {
    id: "8",
    name: "SkillForge",
    website: "https://skillforge.edu",
    description: "Adaptive learning platform using AI to create personalized upskilling paths for enterprise teams, with skill gap analysis and certification tracking.",
    sector: "EdTech",
    stage: "Seed",
    location: "Berlin, Germany",
    founded: 2022,
    employees: "11-50",
    tags: ["education", "AI", "upskilling", "enterprise"],
    signals: [
      { date: "2024-10-05", event: "Launched in DACH region" },
      { date: "2024-07-20", event: "Closed €3M seed round" },
    ],
  },
  {
    id: "9",
    name: "ShieldNet",
    website: "https://shieldnet.security",
    description: "Zero-trust network security platform with AI-powered threat detection, automated incident response, and compliance reporting for mid-market companies.",
    sector: "CyberSecurity",
    stage: "Series B",
    location: "Tel Aviv, Israel",
    founded: 2020,
    employees: "101-250",
    tags: ["security", "zero-trust", "AI", "compliance"],
    signals: [
      { date: "2024-12-10", event: "Raised $35M Series B" },
      { date: "2024-09-05", event: "SOC 2 Type II certification achieved" },
      { date: "2024-05-15", event: "Launched automated incident response" },
    ],
  },
  {
    id: "10",
    name: "CropSense",
    website: "https://cropsense.ag",
    description: "Precision agriculture platform using satellite imagery and IoT sensors for crop health monitoring, yield prediction, and automated irrigation control.",
    sector: "AgTech",
    stage: "Seed",
    location: "Des Moines, IA",
    founded: 2023,
    employees: "11-50",
    tags: ["agriculture", "IoT", "satellite", "precision farming"],
    signals: [
      { date: "2024-08-30", event: "Pilot with 50 farms in Iowa" },
      { date: "2024-06-15", event: "Raised $3.5M seed" },
    ],
  },
  {
    id: "11",
    name: "TalentOS",
    website: "https://talentos.hr",
    description: "All-in-one HR platform with AI-driven recruiting, performance management, and employee engagement tools designed for remote-first companies.",
    sector: "HRTech",
    stage: "Series A",
    location: "Toronto, Canada",
    founded: 2021,
    employees: "51-100",
    tags: ["HR", "recruiting", "AI", "remote work"],
    signals: [
      { date: "2024-11-10", event: "Expanded to US market" },
      { date: "2024-08-01", event: "Series A of $10M closed" },
    ],
  },
  {
    id: "12",
    name: "SpaceHQ",
    website: "https://spacehq.prop",
    description: "Commercial real estate analytics platform using computer vision and foot traffic data to help investors evaluate property performance and market trends.",
    sector: "PropTech",
    stage: "Pre-Seed",
    location: "Miami, FL",
    founded: 2024,
    employees: "1-10",
    tags: ["real estate", "analytics", "computer vision", "investment"],
    signals: [
      { date: "2024-10-01", event: "Accepted into Techstars Miami" },
    ],
  },
];
