/**
 * In-memory mock dataset for the VC Scout app.
 * Used by API routes to provide deterministic data without a database.
 */

import type { Company, Sector, Stage } from "./types";

export const companies: Company[] = [
  {
    id: "c_stripe",
    name: "Stripe",
    website: "https://stripe.com",
    description: "Payments and financial infrastructure for internet businesses.",
    sector: "FinTech",
    stage: "Series B",
    location: "San Francisco, CA",
    founded: 2010,
    employees: "101-500",
    tags: ["payments", "billing", "api", "risk"],
    signals: [
      { date: "2024-11-01", event: "Pricing page available" },
      { date: "2025-01-10", event: "Developer docs prominent" },
    ],
  },
  {
    id: "c_linear",
    name: "Linear",
    website: "https://linear.app",
    description: "Issue tracking and project planning for modern software teams.",
    sector: "SaaS",
    stage: "Series A",
    location: "Remote",
    founded: 2019,
    employees: "51-100",
    tags: ["issue-tracking", "productivity", "workflow"],
    signals: [
      { date: "2025-02-02", event: "Changelog present" },
      { date: "2025-03-12", event: "Careers page found" },
    ],
  },
  {
    id: "c_notion",
    name: "Notion",
    website: "https://www.notion.so",
    description: "All-in-one workspace for docs, wikis, tasks, and knowledge.",
    sector: "SaaS",
    stage: "Series B",
    location: "San Francisco, CA",
    founded: 2013,
    employees: "101-500",
    tags: ["docs", "wiki", "collaboration", "knowledge"],
    signals: [
      { date: "2024-10-18", event: "Templates gallery highlighted" },
      { date: "2025-01-22", event: "Recent product updates section" },
    ],
  },
  {
    id: "c_ramp",
    name: "Ramp",
    website: "https://ramp.com",
    description: "Corporate cards and spend management to help businesses save time and money.",
    sector: "FinTech",
    stage: "Series B",
    location: "New York, NY",
    founded: 2019,
    employees: "101-500",
    tags: ["spend-management", "cards", "accounting"],
    signals: [
      { date: "2025-04-08", event: "Case studies available" },
      { date: "2025-05-03", event: "Pricing/plan information present" },
    ],
  },
  {
    id: "c_ironclad",
    name: "Ironclad",
    website: "https://ironcladapp.com",
    description: "Digital contracting platform for legal teams to manage the contract lifecycle.",
    sector: "LegalTech",
    stage: "Series B",
    location: "San Francisco, CA",
    founded: 2014,
    employees: "101-500",
    tags: ["contracts", "clm", "legal-ops", "workflow"],
    signals: [
      { date: "2025-01-14", event: "Resources/blog section active" },
      { date: "2025-03-28", event: "Integrations listed" },
    ],
  },
  {
    id: "c_vanta",
    name: "Vanta",
    website: "https://vanta.com",
    description: "Automated security compliance (SOC 2, ISO 27001) for fast-growing companies.",
    sector: "CyberSecurity",
    stage: "Series A",
    location: "San Francisco, CA",
    founded: 2018,
    employees: "101-500",
    tags: ["compliance", "soc2", "iso27001", "security"],
    signals: [
      { date: "2025-02-06", event: "Trust center referenced" },
      { date: "2025-04-19", event: "Partner ecosystem highlighted" },
    ],
  },
  {
    id: "c_snyk",
    name: "Snyk",
    website: "https://snyk.io",
    description: "Developer security platform for finding and fixing vulnerabilities.",
    sector: "CyberSecurity",
    stage: "Series B",
    location: "Boston, MA",
    founded: 2015,
    employees: "101-500",
    tags: ["devsecops", "open-source", "vuln-management"],
    signals: [
      { date: "2024-12-12", event: "Documentation hub linked" },
      { date: "2025-02-25", event: "Open source repo links found" },
    ],
  },
  {
    id: "c_watershed",
    name: "Watershed",
    website: "https://watershed.com",
    description: "Sustainability platform for measuring, reporting, and reducing emissions.",
    sector: "Climate",
    stage: "Series A",
    location: "San Francisco, CA",
    founded: 2020,
    employees: "51-100",
    tags: ["sustainability", "carbon", "emisison-accounting", "esg"],
    signals: [
      { date: "2025-01-08", event: "Customer stories available" },
      { date: "2025-03-05", event: "Careers page found" },
    ],
  },
  {
    id: "c_flexport",
    name: "Flexport",
    website: "https://flexport.com",
    description: "Logistics technology platform for global freight forwarding and supply chains.",
    sector: "Logistics",
    stage: "Series B",
    location: "San Francisco, CA",
    founded: 2013,
    employees: "101-500",
    tags: ["freight", "supply-chain", "shipping", "logistics"],
    signals: [
      { date: "2025-02-11", event: "Resource center active" },
      { date: "2025-05-20", event: "Product pages segmented by use case" },
    ],
  },
  {
    id: "c_endeavor",
    name: "Endeavor Health Analytics",
    website: "https://www.endeavorhealth.org",
    description: "Data-driven tools and services to improve patient outcomes and operations.",
    sector: "HealthTech",
    stage: "Seed",
    location: "Chicago, IL",
    founded: 2021,
    employees: "11-50",
    tags: ["healthcare", "analytics", "workflow", "providers"],
    signals: [
      { date: "2025-01-30", event: "Press/news section found" },
      { date: "2025-04-03", event: "Leadership/team page present" },
    ],
  },
  {
    id: "c_duolingo",
    name: "Duolingo",
    website: "https://duolingo.com",
    description: "Language learning platform with gamified lessons and adaptive practice.",
    sector: "EdTech",
    stage: "Series B",
    location: "Pittsburgh, PA",
    founded: 2011,
    employees: "101-500",
    tags: ["education", "language", "consumer", "mobile"],
    signals: [
      { date: "2025-02-17", event: "Blog/news updates present" },
      { date: "2025-03-21", event: "Careers page found" },
    ],
  },
  {
    id: "c_deel",
    name: "Deel",
    website: "https://deel.com",
    description: "Global hiring, payroll, and compliance for distributed teams.",
    sector: "HRTech",
    stage: "Series B",
    location: "Remote",
    founded: 2019,
    employees: "101-500",
    tags: ["payroll", "compliance", "hr", "global"],
    signals: [
      { date: "2025-02-09", event: "Pricing page exists" },
      { date: "2025-06-01", event: "Integration marketplace listed" },
    ],
  },
  {
    id: "c_opendoor",
    name: "Opendoor",
    website: "https://opendoor.com",
    description: "A digital platform for buying and selling homes with speed and certainty.",
    sector: "PropTech",
    stage: "Series B",
    location: "Tempe, AZ",
    founded: 2014,
    employees: "101-500",
    tags: ["real-estate", "marketplace", "transactions"],
    signals: [
      { date: "2025-03-09", event: "Local market pages found" },
      { date: "2025-05-16", event: "Help center present" },
    ],
  },
  {
    id: "c_relay",
    name: "Relay Payments",
    website: "https://relaypayments.com",
    description: "Digital payments network for the trucking and logistics industry.",
    sector: "FinTech",
    stage: "Series A",
    location: "Atlanta, GA",
    founded: 2017,
    employees: "51-100",
    tags: ["trucking", "payments", "logistics", "b2b"],
    signals: [
      { date: "2025-01-18", event: "Industries/use-cases pages present" },
      { date: "2025-04-27", event: "Partner program referenced" },
    ],
  },
  {
    id: "c_supabase",
    name: "Supabase",
    website: "https://supabase.com",
    description: "Open source backend platform (database, auth, storage) for developers.",
    sector: "DataTech",
    stage: "Seed",
    location: "Remote",
    founded: 2020,
    employees: "11-50",
    tags: ["database", "open-source", "developer-tools", "postgres"],
    signals: [
      { date: "2025-02-23", event: "Open source repo linked" },
      { date: "2025-05-30", event: "Docs and examples prominent" },
    ],
  },
];

export const sectors: Sector[] = Array.from(
  new Set(companies.map((c) => c.sector))
).sort();

export const stages: Stage[] = Array.from(new Set(companies.map((c) => c.stage))).sort();

export const locations: string[] = Array.from(
  new Set(companies.map((c) => c.location))
).sort();
